title: Emmanuel Amoateng
logo: /Images/Passport photo.jpg
description: Good looking smarth black man.
#show_downloads: true
#theme: jekyll-theme-minimal
#theme: jekyll-theme-slate
theme: jekyll-theme-time machine
